# Generated by Django 5.2.2 on 2025-09-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taslima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taslima_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('flour', models.IntegerField(blank=True, null=True, verbose_name='طحين')),
                ('salt', models.IntegerField(blank=True, null=True, verbose_name='ملح')),
                ('yeast', models.IntegerField(blank=True, null=True, verbose_name='خميرة')),
                ('oil', models.IntegerField(blank=True, null=True, verbose_name='زيت')),
                ('wood', models.IntegerField(blank=True, null=True, verbose_name='حطب')),
                ('rice', models.IntegerField(blank=True, null=True, verbose_name='رز')),
                ('beans', models.IntegerField(blank=True, null=True, verbose_name='فاصولياء')),
                ('lentils_red', models.IntegerField(blank=True, null=True, verbose_name='عدس أحمر')),
                ('lentils_black', models.IntegerField(blank=True, null=True, verbose_name='عدس أسود')),
                ('pasta', models.IntegerField(blank=True, null=True, verbose_name='معكرونة')),
            ],
        ),
        migrations.CreateModel(
            name='Takiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التكية')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم المالك')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('created_at', models.DateField(verbose_name='تاريخ الانشاء')),
                ('taslim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takiyat', to='manegementdata.taslima')),
            ],
        ),
        migrations.CreateModel(
            name='Makhbaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المخبز')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم المالك')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('created_at', models.DateField(verbose_name='تاريخ الانشاء')),
                ('taslim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makhabiz', to='manegementdata.taslima')),
            ],
        ),
    ]
