# Generated by Django 5.2.2 on 2025-09-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makhbaz',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='makhbaz',
            name='taslim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makhabaz', to='manegementdata.taslima'),
        ),
        migrations.AlterField(
            model_name='takiya',
            name='taslim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takiya', to='manegementdata.taslima'),
        ),
    ]
