# Generated by Django 5.2.2 on 2025-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0002_alter_makhbaz_created_at_alter_makhbaz_taslim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makhbaz',
            name='taslim',
        ),
        migrations.RemoveField(
            model_name='takiya',
            name='taslim',
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='taslimat',
            field=models.ManyToManyField(blank=True, related_name='makhbazat', to='manegementdata.taslima', verbose_name='التسليمات'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='taslimat',
            field=models.ManyToManyField(blank=True, related_name='takaya', to='manegementdata.taslima', verbose_name='التسليمات'),
        ),
    ]
