# Generated by Django 5.2.2 on 2025-09-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0003_remove_makhbaz_taslim_remove_takiya_taslim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makhbaz',
            name='taslimat',
        ),
        migrations.RemoveField(
            model_name='takiya',
            name='taslimat',
        ),
        migrations.AddField(
            model_name='taslima',
            name='makhbaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taslimat', to='manegementdata.makhbaz', verbose_name='المخبز'),
        ),
        migrations.AddField(
            model_name='taslima',
            name='takiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taslimat', to='manegementdata.takiya', verbose_name='التكية'),
        ),
        migrations.AlterField(
            model_name='takiya',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
    ]
