# Generated by Django 5.2.2 on 2025-10-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0004_remove_makhbaz_taslimat_remove_takiya_taslimat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makhbaz',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('مجاني', 'مخبز مجاني'), ('مدعم', 'مخبز مدعوم')], max_length=10, null=True, verbose_name='طبيعة التعاقد'),
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إحداثيات الموقع'),
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='oven_type',
            field=models.CharField(blank=True, choices=[('فرن طينة', 'مخبز بدائي (فرن طينة)'), ('يدوي دوار', 'يدوي دوار'), ('نص آلي', 'نص آلي'), ('آلي', 'آلي')], max_length=20, null=True, verbose_name='نوع الفرن / المخبز'),
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='owner_id',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'رقم الهوية يجب أن يكون 9 أرقام')], verbose_name='رقم هوية صاحب المخبز'),
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='production_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='القدرة الإنتاجية اليومية (كيلو)'),
        ),
        migrations.AddField(
            model_name='makhbaz',
            name='status',
            field=models.CharField(blank=True, choices=[('فعال', 'فعال'), ('متوقف', 'متوقف')], max_length=10, null=True, verbose_name='حالة المخبز'),
        ),
        migrations.AlterField(
            model_name='makhbaz',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AlterField(
            model_name='makhbaz',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الجوال يجب أن يكون 10 أرقام')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='makhbaz',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المخبز'),
        ),
        migrations.AlterField(
            model_name='makhbaz',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم صاحب المخبز'),
        ),
    ]
