# Generated by Django 5.2.2 on 2025-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0005_makhbaz_contract_type_makhbaz_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makhbaz',
            name='governorate',
            field=models.CharField(blank=True, choices=[('الوسطى', 'الوسطى'), ('رفح', 'رفح'), ('خان يونس', 'خان يونس')], max_length=50, null=True, verbose_name='المحافظة'),
        ),
    ]
