# Generated by Django 5.2.2 on 2025-10-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0006_alter_makhbaz_governorate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taslima_makhbaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taslima_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('flour', models.PositiveIntegerField(blank=True, null=True, verbose_name='طحين (كيلو)')),
                ('yeast', models.PositiveIntegerField(blank=True, null=True, verbose_name='خميرة (علبة)')),
                ('salt', models.PositiveIntegerField(blank=True, null=True, verbose_name='ملح (كيلو)')),
                ('sugar', models.PositiveIntegerField(blank=True, null=True, verbose_name='سكر (كيلو)')),
                ('cooking_oil', models.PositiveIntegerField(blank=True, null=True, verbose_name='زيت قلي (لتر)')),
                ('wood', models.PositiveIntegerField(blank=True, null=True, verbose_name='حطب (كيلو)')),
                ('gas', models.PositiveIntegerField(blank=True, null=True, verbose_name='غاز (كيلو)')),
                ('additions', models.TextField(blank=True, null=True, verbose_name='إضافات')),
                ('makhbaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taslimat', to='manegementdata.makhbaz', verbose_name='المخبز')),
            ],
        ),
        migrations.DeleteModel(
            name='Taslima',
        ),
    ]
