# Generated by Django 5.2.2 on 2025-10-02 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0007_taslima_makhbaz_delete_taslima'),
    ]

    operations = [
        migrations.AddField(
            model_name='takiya',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إحداثيات الموقع'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='daily_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='القدرة الإنتاجية اليومية (بالقدر)'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='governorate',
            field=models.CharField(blank=True, choices=[('رفح', 'رفح'), ('خان يونس', 'خان يونس'), ('الوسطى', 'المحافظة الوسطى')], max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='owner_id',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'رقم الهوية يجب أن يكون 9 أرقام')], verbose_name='رقم هوية صاحب التكية'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='pot_capacity',
            field=models.PositiveIntegerField(blank=True, choices=[(80, '80 لتر'), (100, '100 لتر'), (120, '120 لتر'), (150, '150 لتر'), (200, '200 لتر')], null=True, verbose_name='سعة القدور (لتر)'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='status',
            field=models.CharField(blank=True, choices=[('فعال', 'فعال'), ('متوقف', 'متوقف')], max_length=10, null=True, verbose_name='حالة التكية'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='total_pots',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إجمالي عدد القدور'),
        ),
        migrations.AlterField(
            model_name='takiya',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان بالتفصيل'),
        ),
        migrations.AlterField(
            model_name='takiya',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الجوال يجب أن يكون 10 أرقام')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='takiya',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المطبخ / التكية'),
        ),
        migrations.AlterField(
            model_name='takiya',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم صاحب التكية'),
        ),
    ]
