# Generated by Django 5.2.2 on 2025-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0008_takiya_coordinates_takiya_daily_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takiya',
            name='pot_capacity',
        ),
        migrations.AddField(
            model_name='takiya',
            name='pots_100',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد القدور سعة 100 لتر'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='pots_120',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد القدور سعة 120 لتر'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='pots_150',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد القدور سعة 150 لتر'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='pots_200',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد القدور سعة 200 لتر'),
        ),
        migrations.AddField(
            model_name='takiya',
            name='pots_80',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد القدور سعة 80 لتر'),
        ),
    ]
