# Generated by Django 5.2.2 on 2025-10-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0009_remove_takiya_pot_capacity_takiya_pots_100_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taslima_takiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taslima_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('salt', models.PositiveIntegerField(blank=True, null=True, verbose_name='ملح (كيلو)')),
                ('macaroni', models.PositiveIntegerField(blank=True, null=True, verbose_name='معكرونة (كيلو)')),
                ('rice', models.PositiveIntegerField(blank=True, null=True, verbose_name='رز (كيلو)')),
                ('oil', models.PositiveIntegerField(blank=True, null=True, verbose_name='زيت (لتر)')),
                ('peas', models.PositiveIntegerField(blank=True, null=True, verbose_name='بازيلا (علبة 400 جم)')),
                ('lentils', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدس مجروش (كيلو)')),
                ('beans', models.PositiveIntegerField(blank=True, null=True, verbose_name='لوبيا حب (كيلو)')),
                ('sauce', models.PositiveIntegerField(blank=True, null=True, verbose_name='صلصة (علبة 800 جم)')),
                ('luncheon', models.PositiveIntegerField(blank=True, null=True, verbose_name='لانشون (علبة 300 جم)')),
                ('maggi_spice', models.PositiveIntegerField(blank=True, null=True, verbose_name='بهار ماجي (كيلو)')),
                ('vegetable_soup', models.PositiveIntegerField(blank=True, null=True, verbose_name='شوربة خضار (كيلو)')),
                ('seven_spices', models.PositiveIntegerField(blank=True, null=True, verbose_name='٧ بهارات (كيلو)')),
                ('ghee', models.PositiveIntegerField(blank=True, null=True, verbose_name='سمنة (علبة)')),
                ('bulgur', models.PositiveIntegerField(blank=True, null=True, verbose_name='برغل (كيلو)')),
                ('additions', models.TextField(blank=True, null=True, verbose_name='إضافات')),
                ('takiya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taslimat', to='manegementdata.takiya', verbose_name='التكية')),
            ],
        ),
    ]
