# Generated by Django 5.2.2 on 2025-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0010_taslima_takiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='taslima_makhbaz',
            name='until_date',
            field=models.DateField(null=True, blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taslima_takiya',
            name='until_date',
            field=models.DateField(null=True, blank=True, default=None),
            preserve_default=False,
        ),
    ]
