# Generated by Django 5.2.2 on 2025-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0011_taslima_makhbaz_until_date_taslima_takiya_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taslima_makhbaz',
            name='until_date',
            field=models.DateField(blank=True, null=True, verbose_name='حتى تاريخ'),
        ),
        migrations.AlterField(
            model_name='taslima_takiya',
            name='until_date',
            field=models.DateField(blank=True, null=True, verbose_name='حتى تاريخ'),
        ),
    ]
