# Generated by Django 5.2.2 on 2025-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegementdata', '0012_alter_taslima_makhbaz_until_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taslima_takiya',
            name='amount_of_vegetables',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='كمية الخضار'),
        ),
        migrations.AddField(
            model_name='taslima_takiya',
            name='vegetable',
            field=models.TextField(blank=True, null=True, verbose_name='خضار'),
        ),
    ]
